package ExceptionHandling;

public class Example2 {
	public static void main(String[] args) {
		try {
			int a=1/0;
			
		}
		catch (ArithmeticException e) {
			// TODO: handle exception
			try {
				int arr[]= {1,23,4,43,5};
			} catch (ArrayIndexOutOfBoundsException e2) {
				// TODO: handle exception
				System.out.println("Handled");
			}
		}
	}

}
